### ISSUE TITLE
Option to not randomize order of custom pattern

### ISSUE THREAD

**Issue by Abba-** [VictorGrycuk/StreamDeck-KeePass#10]
If custom pattern is chosen, it will still randomize the order of the pattern.
An option to not do that would be appreciated.

**Comment by VictorGrycuk** [comment]
Hi @Abba-, thank you for the issue.
Could you give me an example of a pattern? I will try to reproduce it on my side and see if I can a fix for it.

**Comment by Abba-** [comment]
`dddddsssddddd` from keepass examples: ` 66037!?\80007`   `16804.;>98729`
`dddddsssddddd` from StreamDeck:            ` $824*!498566`  `.9@26,237244`

Note Keepass has a "randomly permutate" checkbox, maybe that is a control that's on by default?
(Possibly [profile.PatternPermutePassword = true;](https://github.com/VictorGrycuk/StreamDeck-KeePass/blob/bbf9859ef19591ff47cee0ce51a6ccdb55213717/StreamDeck-KeePass/StreamDeck-KeePass/KeePassGenerate.cs#L114)  )

![Screenshot 2021-12-22 104148](https://user-images.githubusercontent.com/8104264/147117933-6afa5f2a-8e64-4ffd-8df7-2901f14d7f96.png)

**Comment by VictorGrycuk** [comment]
Thank you for the information, @Abba-!
Adding that checkbox shouldn't be too hard. I will try to get it done in the next few days.

**Comment by VictorGrycuk** [comment]
Hi @Abba-, I created a [beta release](https://github.com/VictorGrycuk/StreamDeck-KeePass/releases/tag/1.5.0-Beta) that includes the option to enable/disable the character permutation.
Could you please validate that it works as intended? If so, I will merge it to master.

Thanks.

**Comment by Abba-** [comment]
Validated, thank you!
