### ISSUE TITLE
Retrieve Not Working

### ISSUE THREAD

**Issue by ghost** [VictorGrycuk/StreamDeck-KeePass#15]
When attempting to use the 'Retrieve' function the plugins logs show:

```
2022-10-20 10:51:05.5986|INFO|BarRaider.SdTools.Logger|The file version is unsupported.

A newer KeePass version is required to open this file
```

I am using:
StreamDeck-KeePass Plugin version 1.5.0 - 1/24/2022

KeePass 2.52 (64-bit)
KeePassLibC (1.x File Support) 1.40.1 - 0x01C2

**Comment by VictorGrycuk** [comment]
Hi @obsidian33, download and install [this version](https://github.com/VictorGrycuk/StreamDeck-KeePass/releases/tag/v1.6.0-beta) and let me know if it fixes it.

**Comment by ghost** [comment]
@VictorGrycuk that fixed it!

**Comment by VictorGrycuk** [comment]
Thanks @obsidian33.
I forgot to update the version on the store. I will have to do it asap.

I will be closing the issue.
