### ISSUE TITLE
Unable to retrieve passwords

### ISSUE THREAD

**Issue by Adde9200** [VictorGrycuk/StreamDeck-KeePass#16]
I've verified that I've used the correct password for my database, but it doesn't retrieve anything from the database.

![image](https://github.com/VictorGrycuk/StreamDeck-KeePass/assets/133674017/ea4fd197-c11c-4810-b842-cff7cba1b2ff)

![image](https://github.com/VictorGrycuk/StreamDeck-KeePass/assets/133674017/1a1ce7ed-5afe-4e47-bf0b-95ee236213af)

I've tried both key file and password, with and without quotes in the text fields

I've also tried an older version but I cannot get it to work. Am I missing anything obvious here?

**Comment by VictorGrycuk** [comment]
Hi @Adde9200!
I don't have my StreamDeck at hand at the moment, but until I can verify myself, try to use path without the double quotes, as: `c:\stuff\testguy.kdbx`. It's the first thing that comes to mind that might cause issues.

But later today I will try it myself to verify if that's the case,

**Comment by Adde9200** [comment]
Thanks for the reply, I tried using no quotes this morning but it doesn't work. My colleague is having the exact same problem.

**Comment by VictorGrycuk** [comment]
Thanks @Adde9200.
I think I was able to reproduce the issue on my pc, and while I work on it, could you please attach the logs for the plugin?
You should find it here: `C:\Users\{user}\AppData\Roaming\Elgato\StreamDeck\Plugins\com.victorgrycuk.keepass.sdPlugin\pluginlog.log`.

The log shouldn't contain any sensitive information, but just check to make sure (and let me know if that's the case because it shouldn't).

**Comment by Adde9200** [comment]
[pluginlog.log](https://github.com/VictorGrycuk/StreamDeck-KeePass/files/11488726/pluginlog.log)

I've attached the log :)

**Comment by VictorGrycuk** [comment]
Thank you!
I see that it is logging `The composite key is invalid!`, I saw the same on my tests. It seems that it's not working the key file option.
I will see what it can be causing the issue, I will let you know as soon as possible!

**Comment by Adde9200** [comment]
I see, I’d also like to add that the issue also happens when using password, not only key file 😊

**Comment by VictorGrycuk** [comment]
That's weird, that did work on my local tests.
Can you upload a log for that case? Delete the old log so it doesn't mix with the previous case.

Thanks!

**Comment by Adde9200** [comment]
I’ll send the logs tomorrow, I’ve just left the stream deck for the day

**Comment by VictorGrycuk** [comment]
@Adde9200 Try [this previous version](https://github.com/VictorGrycuk/StreamDeck-KeePass/releases/tag/v1.6.0), it worked for me.
I will see what was broken between version.

**Comment by VictorGrycuk** [comment]
Looks like the latest released version (1.6.1) is using the previously deprecated `KeeLib.dll`, the previous beta version (1.6.0) uses the KeePass.exe itself instead of the library.

I will release a new version soon.

**Comment by Adde9200** [comment]
Yes, the previous version works! Thank you very much for your help!

**Comment by VictorGrycuk** [comment]
No problem! Glad to hear that it works!
Sorry for releasing a broken version, I need to fix that asap.
