### ISSUE TITLE
v1.6.1 doesn't seem to include the fix in v1.6.0-beta

### ISSUE THREAD

**Issue by ghost** [VictorGrycuk/StreamDeck-KeePass#17]
I previously posted the issue that was resolved in v1.6.0 in [#15](https://github.com/VictorGrycuk/StreamDeck-KeePass/issues/15).
I upgrade to v1.6.1 and the issue is recurring. I rolled-back to v1.6.0 and the issue was resolved.

**Comment by VictorGrycuk** [comment]
Yes, I need to update the version released in the store ASAP.

**Comment by VictorGrycuk** [comment]
I just released the version [1.7.0](https://github.com/VictorGrycuk/StreamDeck-KeePass/releases/tag/v1.7.0) which should contain the fix in 1.6.0-beta.
I will close the issue as soon as the new version is on the marketplace.

**Comment by VictorGrycuk** [comment]
The new version should be live in the market.
I will close this issue.
