### ISSUE TITLE
Key file

### ISSUE THREAD

**Issue by kjetilpp** [VictorGrycuk/StreamDeck-KeePass#6]
Hello! 
How can i use a DB that require a key file?

**Comment by VictorGrycuk** [comment]
Hi @kjetilpp! At the moment that use case is not supported.
However, I will see if it is possible to implement and release a new version.

**Comment by VictorGrycuk** [comment]
Hi @kjetilpp, sorry for the delay.
I created the [1.4.0 pre-release](https://github.com/VictorGrycuk/StreamDeck-KeePass/releases/tag/1.4.0) that adds the option to specify a key file path.

Could you please test it and let me know if this works for you?
Thanks.

**Comment by kjetilpp** [comment]
Hello @VictorGrycuk 
Tested now. 
Are getting the green check box when pressing the button, but no output.

**Comment by VictorGrycuk** [comment]
Thanks @kjetilpp.
Just to make sure, the plugin just copies the content of the selected field into the clipboard. Have you tried to paste after pressing the button?

**Comment by kjetilpp** [comment]
Sorry, my bad... 😭 
Working ✅ ❤️

**Comment by VictorGrycuk** [comment]
@kjetilpp No worries! Glad to know its working!
Now if you don't mind, I will close the issue and see to release it officially.

Thanks!

**Comment by kjetilpp** [comment]
Yes, please do 😃
