### ISSUE TITLE
Suggestion: System-wide hotkeys

### ISSUE THREAD

**Issue by ZehelFenris** [VictorGrycuk/StreamDeck-KeePass#8]
Add the system-wide hotkeys as buttons in the plugin

**Comment by VictorGrycuk** [comment]
Hi @ZehelFenris, could you give me an example of how you would use a system wide hotkey with the plugin?

As a side note, updates on my plugins are on hold for the moment. But I will work on it as soon as I can.

**Comment by ZehelFenris** [comment]
So when you click on the button for "Global auto-type" it would go and find the keybinding for it and then use it or in case of KeePass don't have a way to auto-detect it then some way to enter the keybinding yourself.
Could be one key with a dropdown to select which one of the four system-wide hotkeys you want to use
![dghssfh](https://user-images.githubusercontent.com/43239740/133032874-2af3c672-f13c-4dc3-a6b9-17a28bc468dc.png)

**Comment by VictorGrycuk** [comment]
Thank you, if the KeePass sdk exposes that functionality, it shouldn't be too difficult to implement.

**Comment by VictorGrycuk** [comment]
Hi @ZehelFenris, sorry for the long hiatus.
I have been looking for hot keys support for the KeePass Lib, but doesn't seem to be any.

However, if you want to trigger any of the system-wide hot keys of KeePass, you could use a plugin like [Super Macro](https://github.com/BarRaider/streamdeck-supermacro) to trigger it.

**Comment by ZehelFenris** [comment]
Ended up using the default Hotkey under Systems.
I had just hoped that was a way that would do so my type passwords would still be correct even if the hotkeys got changed guess I have to think twice before I change any hotkeys in KeePass :D

**Comment by VictorGrycuk** [comment]
This plugin communicates directly with the DB, not with the KeePass app, so it has no access to the hot key of the app.
That would require this plugin to communicate with the app instead of the DB, but that's out of the current scope of this plugin.

If you don't mind, I will close this issue.
